function ( BuildSlnTree currdir my_head_list my_src_list my_include_dirs )
    set ( tmp_header_list  "" )
    set ( tmp_src_list     "" )
    set ( tmp_include_dirs "" )

    message ( STATUS "BuildSlnTree: The currdir is ${currdir}" )
    file ( GLOB_RECURSE FOUND_FILES LIST_DIRECTORIES true RELATIVE ${currdir} * )

    message( STATUS "BuildSlnTree: FOUND_FILES = ${FOUND_FILES}" )

    foreach ( child ${FOUND_FILES} )
        message ( STATUS "BuildSlnTree:child=${child}" )
        set( candidate_dir ${currdir}/${child} )
        if ( IS_DIRECTORY ${candidate_dir} )
            file ( GLOB header_files "${candidate_dir}/*.h" )
            file ( GLOB src_files    "${candidate_dir}/*.cpp" )
            file ( GLOB cuda_src_files "${candidate_dir}/*.cu" )
            file ( GLOB hpp_files    "${candidate_dir}/*.hpp" )
            
            list ( APPEND header_files ${hpp_files} )
            
            list ( LENGTH header_files n_header_files )
            if ( NOT ( ${n_header_files} EQUAL 0 ) )
                list ( APPEND tmp_include_dirs ${candidate_dir} )
            endif()
            
            source_group ( "${child}" FILES ${header_files} )
            source_group ( "${child}" FILES ${src_files}    )
            source_group ( "${child}" FILES ${cuda_src_files})
            
            list ( APPEND tmp_header_list ${header_files} )
            list ( APPEND tmp_src_list  ${src_files} )
            list ( APPEND tmp_src_list  ${cuda_src_files} )
        else()
            file ( GLOB header_files "${currdir}/*.h" )
            file ( GLOB src_files    "${currdir}/*.cpp" )
            file ( GLOB cuda_src_files "${currdir}/*.cu" )
            source_group ( "ROOT" FILES ${header_files} )
            source_group ( "ROOT" FILES ${src_files}    )
            source_group ( "ROOT" FILES ${cuda_src_files} )
            list ( APPEND tmp_header_list ${header_files} )
            list ( APPEND tmp_src_list  ${src_files} )
            list ( APPEND tmp_src_list  ${cuda_src_files} )
        endif()
    endforeach()
    set ( ${my_head_list} ${tmp_header_list} PARENT_SCOPE )
    set ( ${my_src_list} ${tmp_src_list} PARENT_SCOPE )
    set ( ${my_include_dirs} ${tmp_include_dirs} PARENT_SCOPE ) 
endfunction()